import { Category, Post, Resource, Author } from "@/types/sanity";

export const authors: Author[] = [
  {
    name: "Alex Chen",
    slug: "alex-chen",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    bio: "Senior Security Engineer with 10+ years of experience",
  },
  {
    name: "Sarah Kim",
    slug: "sarah-kim",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    bio: "AI/ML Researcher and Technical Writer",
  },
  {
    name: "Mike Johnson",
    slug: "mike-johnson",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    bio: "DevOps Lead and Cloud Architect",
  },
];

export const categories: Category[] = [
  {
    title: "Technology",
    slug: "technology",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop",
    badge: "Tech",
    description: "Latest technology trends and innovations",
    articleCount: 24,
    tag: "Tech",
  },
  {
    title: "AI",
    slug: "ai",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop",
    badge: "AI",
    description: "Machine learning, deep learning, and AI applications",
    articleCount: 18,
    tag: "AI",
  },
  {
    title: "Cybersecurity",
    slug: "cybersecurity",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600&fit=crop",
    badge: "Security",
    description: "Security best practices and threat prevention",
    articleCount: 32,
    tag: "Cybersecurity",
  },
  {
    title: "Cloud",
    slug: "cloud",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop",
    badge: "Cloud",
    description: "AWS, Azure, GCP and cloud architecture",
    articleCount: 21,
    tag: "Cloud",
  },
  {
    title: "Linux",
    slug: "linux",
    image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&h=600&fit=crop",
    badge: "Linux",
    description: "Linux administration and command line mastery",
    articleCount: 28,
    tag: "Tech",
  },
  {
    title: "Networking",
    slug: "networking",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop",
    badge: "Network",
    description: "Network protocols, configuration, and troubleshooting",
    articleCount: 15,
    tag: "Tech",
  },
  {
    title: "Web Development",
    slug: "web-development",
    image: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&h=600&fit=crop",
    badge: "WebDev",
    description: "Frontend, backend, and full-stack development",
    articleCount: 42,
    tag: "Tech",
  },
  {
    title: "DevOps",
    slug: "devops",
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&h=600&fit=crop",
    badge: "DevOps",
    description: "CI/CD, automation, and infrastructure as code",
    articleCount: 19,
    tag: "DevOps",
  },
  {
    title: "Tools",
    slug: "tools",
    image: "https://images.unsplash.com/photo-1581287053822-fd7bf4f4bfec?w=800&h=600&fit=crop",
    badge: "Tools",
    description: "Essential tools and software for developers",
    articleCount: 27,
    tag: "Tech",
  },
  {
    title: "Notes",
    slug: "notes",
    image: "https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop",
    badge: "Notes",
    description: "Quick reference notes and summaries",
    articleCount: 45,
    tag: "Tech",
  },
  {
    title: "Roadmaps",
    slug: "roadmaps",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop",
    badge: "Roadmap",
    description: "Career paths and learning roadmaps",
    articleCount: 12,
    tag: "Tech",
  },
  {
    title: "Cheatsheets",
    slug: "cheatsheets",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop",
    badge: "Cheatsheet",
    description: "Quick reference guides and cheatsheets",
    articleCount: 35,
    tag: "Tech",
  },
];

export const posts: Post[] = [
  {
    title: "Getting Started with Machine Learning in 2024",
    slug: "getting-started-machine-learning-2024",
    coverImage: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=600&fit=crop",
    author: authors[1],
    category: "Artificial Intelligence",
    categorySlug: "ai",
    publishedAt: "2024-01-15",
    readTime: 8,
    excerpt: "A comprehensive guide to starting your machine learning journey with the latest tools and frameworks.",
    body: "Machine learning has become one of the most sought-after skills...",
    featured: true,
  },
  {
    title: "Essential Linux Commands Every Developer Should Know",
    slug: "essential-linux-commands",
    coverImage: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&h=600&fit=crop",
    author: authors[0],
    category: "Linux",
    categorySlug: "linux",
    publishedAt: "2024-01-12",
    readTime: 6,
    excerpt: "Master the command line with these essential Linux commands for daily development tasks.",
    body: "The Linux command line is a powerful tool...",
    featured: false,
  },
  {
    title: "Understanding Zero Trust Security Architecture",
    slug: "zero-trust-security-architecture",
    coverImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=600&fit=crop",
    author: authors[0],
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    publishedAt: "2024-01-10",
    readTime: 10,
    excerpt: "Learn how Zero Trust architecture is revolutionizing enterprise security strategies.",
    body: "Zero Trust is not just a buzzword...",
    featured: true,
  },
  {
    title: "Building Scalable APIs with Node.js and Express",
    slug: "scalable-apis-nodejs-express",
    coverImage: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&h=600&fit=crop",
    author: authors[2],
    category: "Web Development",
    categorySlug: "web-development",
    publishedAt: "2024-01-08",
    readTime: 12,
    excerpt: "Best practices for building production-ready APIs that can handle millions of requests.",
    body: "Building scalable APIs requires careful planning...",
    featured: false,
  },
  {
    title: "Kubernetes for Beginners: A Complete Guide",
    slug: "kubernetes-beginners-guide",
    coverImage: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&h=600&fit=crop",
    author: authors[2],
    category: "DevOps",
    categorySlug: "devops",
    publishedAt: "2024-01-05",
    readTime: 15,
    excerpt: "Everything you need to know to get started with Kubernetes container orchestration.",
    body: "Kubernetes has become the de facto standard...",
    featured: true,
  },
  {
    title: "AWS vs Azure vs GCP: Cloud Comparison 2024",
    slug: "aws-azure-gcp-comparison-2024",
    coverImage: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop",
    author: authors[2],
    category: "Cloud Computing",
    categorySlug: "cloud",
    publishedAt: "2024-01-03",
    readTime: 9,
    excerpt: "An in-depth comparison of the three major cloud providers for enterprise workloads.",
    body: "Choosing the right cloud provider...",
    featured: false,
  },
  {
    title: "React 19 New Features and Best Practices",
    slug: "react-19-features-best-practices",
    coverImage: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=600&fit=crop",
    author: authors[1],
    category: "Web Development",
    categorySlug: "web-development",
    publishedAt: "2024-01-01",
    readTime: 7,
    excerpt: "Explore the latest features in React 19 and learn how to use them effectively.",
    body: "React 19 brings exciting new features...",
    featured: false,
  },
  {
    title: "Network Security Fundamentals",
    slug: "network-security-fundamentals",
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop",
    author: authors[0],
    category: "Networking",
    categorySlug: "networking",
    publishedAt: "2023-12-28",
    readTime: 11,
    excerpt: "Understanding the core concepts of network security and common attack vectors.",
    body: "Network security is critical in today's connected world...",
    featured: false,
  },
  {
    title: "Introduction to Large Language Models",
    slug: "introduction-large-language-models",
    coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop",
    author: authors[1],
    category: "Artificial Intelligence",
    categorySlug: "ai",
    publishedAt: "2023-12-25",
    readTime: 13,
    excerpt: "Deep dive into how LLMs work and their applications in modern software.",
    body: "Large Language Models have revolutionized...",
    featured: true,
  },
];

export const resources: Resource[] = [
  {
    title: "Complete Linux Command Cheatsheet",
    slug: "linux-command-cheatsheet",
    type: "Cheatsheets",
    image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&h=600&fit=crop",
    description: "Essential Linux commands organized by category for quick reference.",
    downloadUrl: "/downloads/linux-cheatsheet.pdf",
  },
  {
    title: "DevOps Engineer Roadmap 2024",
    slug: "devops-roadmap-2024",
    type: "Roadmaps",
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&h=600&fit=crop",
    description: "A comprehensive roadmap to becoming a DevOps engineer from scratch.",
    downloadUrl: "/downloads/devops-roadmap.pdf",
  },
  {
    title: "Git & GitHub Complete Guide",
    slug: "git-github-guide",
    type: "Guides",
    image: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&h=600&fit=crop",
    description: "Master version control with Git and GitHub collaboration workflows.",
    downloadUrl: "/downloads/git-guide.pdf",
  },
  {
    title: "Kubernetes Quick Reference",
    slug: "kubernetes-quick-reference",
    type: "Cheatsheets",
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&h=600&fit=crop",
    description: "kubectl commands and Kubernetes concepts at your fingertips.",
    downloadUrl: "/downloads/k8s-cheatsheet.pdf",
  },
  {
    title: "Cybersecurity Career Roadmap",
    slug: "cybersecurity-roadmap",
    type: "Roadmaps",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600&fit=crop",
    description: "Your path to becoming a cybersecurity professional.",
  },
  {
    title: "AWS Services Overview Notes",
    slug: "aws-services-notes",
    type: "Notes",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop",
    description: "Comprehensive notes on major AWS services and use cases.",
    downloadUrl: "/downloads/aws-notes.pdf",
  },
  {
    title: "Docker Essentials Toolkit",
    slug: "docker-essentials",
    type: "Tools",
    image: "https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800&h=600&fit=crop",
    description: "Essential Docker commands, Dockerfile templates, and compose examples.",
    downloadUrl: "/downloads/docker-toolkit.zip",
  },
  {
    title: "JavaScript ES6+ Cheatsheet",
    slug: "javascript-es6-cheatsheet",
    type: "Cheatsheets",
    image: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&h=600&fit=crop",
    description: "Modern JavaScript features and syntax quick reference.",
    downloadUrl: "/downloads/js-cheatsheet.pdf",
  },
  {
    title: "Python for Data Science Notes",
    slug: "python-data-science-notes",
    type: "Notes",
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&h=600&fit=crop",
    description: "NumPy, Pandas, and Matplotlib essentials for data analysis.",
  },
];
