import { authors } from "@/lib/authors";
import type { Post } from "@/types/sanity";

/** Blog posts linked from Interesting Tricks cards — edit via content/interesting-tricks.json */
export const trickBlogPosts: Post[] = [
  {
    title: "How to Copy Text From PC to Mobile (5 Easy Methods)",
    slug: "copy-text-pc-to-mobile",
    coverImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
    author: authors[1],
    category: "Productivity",
    categorySlug: "tools",
    publishedAt: "2026-02-10",
    readTime: 5,
    excerpt: "Share clipboard text between your computer and phone using built-in tools and free apps.",
    body: "Copying text between devices is a daily workflow...",
    featured: true,
  },
  {
    title: "How to Find Your Wi-Fi Password on Windows",
    slug: "find-wifi-password-windows",
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop",
    author: authors[0],
    category: "Networking",
    categorySlug: "networking",
    publishedAt: "2026-02-08",
    readTime: 4,
    excerpt: "Recover a saved Wi-Fi password using Settings, Control Panel, or PowerShell.",
    body: "If you forgot your network password but your PC is already connected...",
    featured: false,
  },
  {
    title: "Speed Up a Slow Laptop in 10 Minutes",
    slug: "speed-up-slow-laptop",
    coverImage: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop",
    author: authors[2],
    category: "Tools",
    categorySlug: "tools",
    publishedAt: "2026-02-05",
    readTime: 6,
    excerpt: "Disable startup apps, clear temp files, and tune power settings for a faster machine.",
    body: "A sluggish laptop often needs maintenance rather than new hardware...",
    featured: false,
  },
  {
    title: "Block Ads on Android Without Root",
    slug: "block-ads-android-no-root",
    coverImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=600&fit=crop",
    author: authors[1],
    category: "Mobile",
    categorySlug: "tools",
    publishedAt: "2026-02-03",
    readTime: 7,
    excerpt: "Use private DNS, browser settings, and trusted apps to reduce ads safely.",
    body: "You do not need root access to cut down most mobile ads...",
    featured: true,
  },
  {
    title: "Share Mobile Internet to PC via USB Tethering",
    slug: "usb-tethering-mobile-to-pc",
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop",
    author: authors[2],
    category: "Networking",
    categorySlug: "networking",
    publishedAt: "2026-01-28",
    readTime: 5,
    excerpt: "A stable USB connection often beats Wi-Fi hotspot for speed and battery life.",
    body: "USB tethering lets your PC use your phone's data connection directly...",
    featured: false,
  },
  {
    title: "Recover Deleted Files From Recycle Bin on Windows",
    slug: "recover-deleted-files-windows",
    coverImage: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop",
    author: authors[0],
    category: "Tools",
    categorySlug: "tools",
    publishedAt: "2026-01-25",
    readTime: 5,
    excerpt: "Restore recently deleted files before they are overwritten permanently.",
    body: "The Recycle Bin is your first stop after an accidental delete...",
    featured: false,
  },
  {
    title: "Take Scrolling Screenshots on Your Phone",
    slug: "scrolling-screenshot-phone",
    coverImage: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop",
    author: authors[1],
    category: "Mobile",
    categorySlug: "tools",
    publishedAt: "2026-01-20",
    readTime: 4,
    excerpt: "Capture long pages on Android and iOS with built-in scroll capture tools.",
    body: "Scrolling screenshots are perfect for chats, articles, and receipts...",
    featured: true,
  },
  {
    title: "Use Your Phone as a Webcam for PC",
    slug: "phone-as-webcam-for-pc",
    coverImage: "https://images.unsplash.com/photo-1587825140702-d63f4f988575?w=800&h=600&fit=crop",
    author: authors[2],
    category: "Productivity",
    categorySlug: "tools",
    publishedAt: "2026-01-18",
    readTime: 6,
    excerpt: "Turn your smartphone into a high-quality webcam with free companion apps.",
    body: "Built-in laptop cameras are often mediocre; your phone camera is not...",
    featured: false,
  },
  {
    title: "Force Dark Mode on Any Website",
    slug: "force-dark-mode-any-website",
    coverImage: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&h=600&fit=crop",
    author: authors[1],
    category: "Productivity",
    categorySlug: "tools",
    publishedAt: "2026-01-15",
    readTime: 4,
    excerpt: "Browser extensions and flags that darken sites without native dark themes.",
    body: "Not every site ships a dark mode, but your browser can help...",
    featured: false,
  },
  {
    title: "Send Large Files Without Email Limits",
    slug: "send-large-files-without-email",
    coverImage: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=600&fit=crop",
    author: authors[0],
    category: "Productivity",
    categorySlug: "tools",
    publishedAt: "2026-01-12",
    readTime: 5,
    excerpt: "Cloud links, P2P tools, and split archives for files bigger than inbox caps.",
    body: "Email providers cap attachment sizes; these methods do not...",
    featured: false,
  },
  {
    title: "Stay Safe on Public Wi-Fi",
    slug: "stay-safe-public-wifi",
    coverImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600&fit=crop",
    author: authors[0],
    category: "Cybersecurity",
    categorySlug: "cybersecurity",
    publishedAt: "2026-01-10",
    readTime: 8,
    excerpt: "VPNs, HTTPS, and firewall habits that protect you on coffee-shop networks.",
    body: "Public Wi-Fi is convenient but exposes you to interception risks...",
    featured: true,
  },
  {
    title: "Check and Improve Phone Battery Health",
    slug: "improve-phone-battery-health",
    coverImage: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop",
    author: authors[1],
    category: "Mobile",
    categorySlug: "tools",
    publishedAt: "2026-01-08",
    readTime: 6,
    excerpt: "Read battery stats, calibrate habits, and slow degradation over time.",
    body: "Battery health affects how long your phone lasts on a charge...",
    featured: false,
  },
  {
    title: "Use a Laptop as a Second Monitor",
    slug: "laptop-as-second-monitor",
    coverImage: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop",
    author: authors[2],
    category: "Productivity",
    categorySlug: "tools",
    publishedAt: "2026-01-05",
    readTime: 7,
    excerpt: "Windows and macOS features to extend your desktop without buying new hardware.",
    body: "A spare laptop can become a wireless or wired second display...",
    featured: false,
  },
  {
    title: "Enable Clipboard History on Windows",
    slug: "enable-clipboard-history-windows",
    coverImage: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop",
    author: authors[0],
    category: "Productivity",
    categorySlug: "tools",
    publishedAt: "2026-01-03",
    readTime: 3,
    excerpt: "Pin multiple copied items and sync clipboard across Windows devices.",
    body: "Clipboard history saves everything you copy after you turn it on...",
    featured: false,
  },
];
